# workers/logo-cdn/wrangler.toml
name = "logo-cdn"
main = "index.ts"
compatibility_date = "2025-12-01"
workers_dev = true

# R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "easyepg-logos"

[vars]
ENVIRONMENT = "production"
